package edu.guilford.horsedesign;

import java.awt.Color;

public class BodyPanel extends javax.swing.JPanel {

    HorsePanel hPanel;

    public HorsePanel gethPanel() {
        return hPanel;
    }

    public void sethPanel(HorsePanel hPanel) {
        this.hPanel = hPanel;
    }

    public BodyPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blackButton = new javax.swing.JButton();
        greyButton = new javax.swing.JButton();
        whiteButton = new javax.swing.JButton();
        palominoButton = new javax.swing.JButton();
        brownButton = new javax.swing.JButton();
        creamButton = new javax.swing.JButton();
        darkBrownButton = new javax.swing.JButton();
        lightPalominoButton = new javax.swing.JButton();
        chestnutButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        blackButton.setBackground(new java.awt.Color(0, 0, 0));
        blackButton.setOpaque(true);
        blackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackButtonActionPerformed(evt);
            }
        });

        greyButton.setBackground(new java.awt.Color(102, 102, 102));
        greyButton.setOpaque(true);
        greyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greyButtonActionPerformed(evt);
            }
        });

        whiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteButtonActionPerformed(evt);
            }
        });

        palominoButton.setBackground(new java.awt.Color(188, 160, 62));
        palominoButton.setOpaque(true);
        palominoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                palominoButtonActionPerformed(evt);
            }
        });

        brownButton.setBackground(new java.awt.Color(118, 64, 5));
        brownButton.setOpaque(true);
        brownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownButtonActionPerformed(evt);
            }
        });

        creamButton.setBackground(new java.awt.Color(245, 244, 201));
        creamButton.setOpaque(true);
        creamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creamButtonActionPerformed(evt);
            }
        });

        darkBrownButton.setBackground(new java.awt.Color(65, 35, 5));
        darkBrownButton.setOpaque(true);
        darkBrownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkBrownButtonActionPerformed(evt);
            }
        });

        lightPalominoButton.setBackground(new java.awt.Color(220, 198, 133));
        lightPalominoButton.setOpaque(true);
        lightPalominoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightPalominoButtonActionPerformed(evt);
            }
        });

        chestnutButton.setBackground(new java.awt.Color(169, 89, 11));
        chestnutButton.setOpaque(true);
        chestnutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chestnutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(brownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(palominoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                            .addComponent(blackButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lightPalominoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(greyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(chestnutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(creamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darkBrownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(whiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blackButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(greyButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(whiteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(creamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(palominoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(brownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lightPalominoButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(darkBrownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chestnutButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void blackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blackButtonActionPerformed
        // TODO add your handling code here:
        Color bLColor = this.blackButton.getBackground();
        hPanel.bodyColorset(bLColor);
    }//GEN-LAST:event_blackButtonActionPerformed

    private void greyButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_greyButtonActionPerformed
        // TODO add your handling code here:
        Color gColor = this.greyButton.getBackground();
        hPanel.bodyColorset(gColor);
    }//GEN-LAST:event_greyButtonActionPerformed

    private void whiteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_whiteButtonActionPerformed
        // TODO add your handling code here:
        Color wColor = this.whiteButton.getBackground();
        hPanel.bodyColorset(wColor);
    }//GEN-LAST:event_whiteButtonActionPerformed

    private void palominoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_palominoButtonActionPerformed
        // TODO add your handling code here:
        Color pColor = this.palominoButton.getBackground();
        hPanel.bodyColorset(pColor);
    }//GEN-LAST:event_palominoButtonActionPerformed

    private void brownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brownButtonActionPerformed
        // TODO add your handling code here:
        Color bColor = this.brownButton.getBackground();
        hPanel.bodyColorset(bColor);
    }//GEN-LAST:event_brownButtonActionPerformed

    private void creamButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creamButtonActionPerformed
        // TODO add your handling code here:
        Color cColor = this.creamButton.getBackground();
        hPanel.bodyColorset(cColor);
    }//GEN-LAST:event_creamButtonActionPerformed

    private void darkBrownButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkBrownButtonActionPerformed
        // TODO add your handling code here:
        Color dBColor = this.darkBrownButton.getBackground();
        hPanel.bodyColorset(dBColor);
    }//GEN-LAST:event_darkBrownButtonActionPerformed

    private void lightPalominoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightPalominoButtonActionPerformed
        // TODO add your handling code here:
        Color lPColor = this.lightPalominoButton.getBackground();
        hPanel.bodyColorset(lPColor);
    }//GEN-LAST:event_lightPalominoButtonActionPerformed

    private void chestnutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chestnutButtonActionPerformed
        // TODO add your handling code here:
        Color ccColor = this.chestnutButton.getBackground();
        hPanel.bodyColorset(ccColor);
    }//GEN-LAST:event_chestnutButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blackButton;
    private javax.swing.JButton brownButton;
    private javax.swing.JButton chestnutButton;
    private javax.swing.JButton creamButton;
    private javax.swing.JButton darkBrownButton;
    private javax.swing.JButton greyButton;
    private javax.swing.JButton lightPalominoButton;
    private javax.swing.JButton palominoButton;
    private javax.swing.JButton whiteButton;
    // End of variables declaration//GEN-END:variables
}
