package edu.guilford.horsedesign;

import java.awt.Color;

public class ManePanel extends javax.swing.JPanel {

    HorsePanel hPanel;

    public HorsePanel gethPanel() {
        return hPanel;
    }

    public void sethPanel(HorsePanel hPanel) {
        this.hPanel = hPanel;
    }

    public ManePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        blackButton = new javax.swing.JButton();
        greyButton = new javax.swing.JButton();
        whiteButton = new javax.swing.JButton();
        brownButton = new javax.swing.JButton();
        brown2Button = new javax.swing.JButton();
        creamButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        blackButton.setBackground(new java.awt.Color(0, 0, 0));
        blackButton.setOpaque(true);
        blackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blackButtonActionPerformed(evt);
            }
        });

        greyButton.setBackground(new java.awt.Color(102, 102, 102));
        greyButton.setOpaque(true);
        greyButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                greyButtonActionPerformed(evt);
            }
        });

        whiteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                whiteButtonActionPerformed(evt);
            }
        });

        brownButton.setBackground(new java.awt.Color(117, 102, 48));
        brownButton.setOpaque(true);
        brownButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brownButtonActionPerformed(evt);
            }
        });

        brown2Button.setBackground(new java.awt.Color(130, 104, 24));
        brown2Button.setOpaque(true);
        brown2Button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brown2ButtonActionPerformed(evt);
            }
        });

        creamButton.setBackground(new java.awt.Color(245, 244, 201));
        creamButton.setOpaque(true);
        creamButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creamButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(brown2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING,
                                                                false)
                                                        .addComponent(brownButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 1,
                                                                Short.MAX_VALUE)
                                                        .addComponent(blackButton,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 67,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(18, 18, 18)
                                                .addComponent(greyButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(creamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 1,
                                                Short.MAX_VALUE)
                                        .addComponent(whiteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(28, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(blackButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(greyButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(whiteButton, javax.swing.GroupLayout.DEFAULT_SIZE, 60,
                                                Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(creamButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(brownButton, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(brown2Button, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(29, Short.MAX_VALUE)));
    }// </editor-fold>//GEN-END:initComponents

    private void blackButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_blackButtonActionPerformed
        // TODO add your handling code here:
        Color bLColor = this.blackButton.getBackground();
        // Color clearColor = new Color(60, 60, 60, 220);
        // hPanel.horseClear(clearColor);
        hPanel.maneColorset(bLColor);
    }// GEN-LAST:event_blackButtonActionPerformed

    private void greyButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_greyButtonActionPerformed
        // TODO add your handling code here:
        Color gColor = this.greyButton.getBackground();
        Color clearColor = new Color(60, 60, 60, 220);
        hPanel.horseClear(clearColor);
        hPanel.maneColorset(gColor);
    }// GEN-LAST:event_greyButtonActionPerformed

    private void whiteButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_whiteButtonActionPerformed
        // TODO add your handling code here:
        Color wColor = this.whiteButton.getBackground();
        Color clearColor = new Color(60, 60, 60, 220);
        hPanel.horseClear(clearColor);
        hPanel.maneColorset(wColor);
    }// GEN-LAST:event_whiteButtonActionPerformed

    private void brownButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_brownButtonActionPerformed
        // TODO add your handling code here:
        Color bbColor = this.brownButton.getBackground();
        Color clearColor = new Color(60, 60, 60, 220);
        hPanel.horseClear(clearColor);
        hPanel.maneColorset(bbColor);
    }// GEN-LAST:event_brownButtonActionPerformed

    private void brown2ButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_brown2ButtonActionPerformed
        // TODO add your handling code here:
        Color bColor = this.brown2Button.getBackground();
        Color clearColor = new Color(60, 60, 60, 220);
        hPanel.horseClear(clearColor);
        hPanel.maneColorset(bColor);
    }// GEN-LAST:event_brown2ButtonActionPerformed

    private void creamButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_creamButtonActionPerformed
        // TODO add your handling code here:
        Color cColor = this.creamButton.getBackground();
        Color clearColor = new Color(60, 60, 60, 220);
        hPanel.horseClear(clearColor);
        hPanel.maneColorset(cColor);
    }// GEN-LAST:event_creamButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton blackButton;
    private javax.swing.JButton brown2Button;
    private javax.swing.JButton brownButton;
    private javax.swing.JButton creamButton;
    private javax.swing.JButton greyButton;
    private javax.swing.JButton whiteButton;
    // End of variables declaration//GEN-END:variables
}
